[package]
name = "wed"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cuducos/wed"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.35"
clap = { version = "4.5.2", features = ["derive"] }
home = "0.5.9"
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
clippy = "0.0.302"
tempdir = "0.3.7"
