[package]
name = "wed"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cuducos/wed"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
clap = { version = "4.2.5", features = ["derive"] }
home = "0.5.5"
reqwest = { version = "0.11.17", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
clippy = "0.0.302"
float-cmp = "0.9.0"
wiremock = "0.5.18"
